import { FormStage } from "@/types/horse";

export const arabicFormStages: FormStage[] = [
  {
    id: "basic",
    title: "المعلومات الأساسية",
    description: "تفاصيل الحصان الأساسية والتعريف",
    fields: ["name", "arabicName", "breed", "gender", "birthDate", "color", "height", "weight", "registrationNumber", "passportNumber", "microchipId"],
    isComplete: false,
    isRequired: true,
  },
  {
    id: "ownership",
    title: "الملكية",
    description: "تفاصيل المالك",
    fields: ["ownerType", "ownerName", "ownerContact"],
    isComplete: false,
    isRequired: true,
  },
  {
    id: "pedigree",
    title: "النسب",
    description: "النسب والأصول",
    fields: ["sire", "dam", "bloodlineOrigin"],
    isComplete: false,
    isRequired: false,
  },
  {
    id: "health",
    title: "الصحة والطب",
    description: "التاريخ الطبي والحالة",
    fields: ["healthStatus", "vaccinationStatus", "lastVetCheckup", "medicalConditions", "allergies"],
    isComplete: false,
    isRequired: true,
  },
  {
    id: "training",
    title: "التدريب والأداء",
    description: "مستوى التدريب والإنجازات",
    fields: ["trainingLevel", "disciplines", "competitionHistory", "achievements"],
    isComplete: false,
    isRequired: false,
  },
  {
    id: "stable",
    title: "إدارة الإسطبل",
    description: "تفاصيل الإسكان والرعاية",
    fields: ["stallNumber", "feedingSchedule", "exerciseRoutine", "specialNeeds"],
    isComplete: false,
    isRequired: false,
  },
  {
    id: "insurance",
    title: "التأمين والمالية",
    description: "التأمين والتقييم",
    fields: ["insured", "insuranceProvider", "insuranceValue", "purchasePrice", "marketValue"],
    isComplete: false,
    isRequired: false,
  },
  {
    id: "documents",
    title: "الوثائق والصور",
    description: "رفع الملفات والصور",
    fields: ["images", "documents"],
    isComplete: false,
    isRequired: false,
  },
];
