
import { z } from "zod";

export const horseFormSchema = z.object({
  name: z.string().min(1, "Name is required"),
  arabicName: z.string().optional(),
  breed: z.string().min(1, "Breed is required"),
  gender: z.enum(["stallion", "mare", "gelding"]),
  birthDate: z.string().min(1, "Birth date is required"),
  color: z.string().min(1, "Color is required"),
  height: z.number().optional(),
  weight: z.number().optional(),
  ownerType: z.enum(["individual", "company", "partnership"]),
  ownerName: z.string().min(1, "Owner name is required"),
  ownerContact: z.string().min(1, "Owner contact is required"),
  registrationNumber: z.string().optional(),
  passportNumber: z.string().optional(),
  microchipId: z.string().optional(),
  sire: z.string().optional(),
  dam: z.string().optional(),
  bloodlineOrigin: z.string().optional(),
  healthStatus: z.enum(["healthy", "under_treatment", "quarantine"]),
  vaccinationStatus: z.enum(["up_to_date", "partial", "none"]),
  lastVetCheckup: z.string().optional(),
  medicalConditions: z.string().optional(),
  allergies: z.string().optional(),
  trainingLevel: z.string().optional(),
  disciplines: z.string().optional(),
  competitionHistory: z.string().optional(),
  achievements: z.string().optional(),
  currentLocation: z.string().optional(),
  stallNumber: z.string().optional(),
  feedingSchedule: z.string().optional(),
  exerciseRoutine: z.string().optional(),
  specialNeeds: z.string().optional(),
  insured: z.boolean(),
  insuranceProvider: z.string().optional(),
  insuranceValue: z.number().optional(),
  purchasePrice: z.number().optional(),
  marketValue: z.number().optional(),
  images: z.array(z.string()),
  documents: z.array(z.string()),
  status: z.enum(["active", "inactive", "transferred", "deceased"]),
});

export type HorseFormValues = z.infer<typeof horseFormSchema>;
